### ISSUE TITLE
Tag based on select

### ISSUE THREAD

**Issue by growdev** [ConvertKit/convertkit-gravity-forms#11]
Use case:
A form has a select and use the select's value as a tag passed to the subscribe.

ref: PS slack convo with @jivedig

**Comment by JiveDig** [comment]
This is a select field and the ‘value’ of each option could/should be passed as a tag. This should work for select/checkbox/radio IMO. This would be a really powerful addition IMO. Right now we're stuck with code (http://help.convertkit.com/article/34-build-a-custom-tag-select-box), but this allows a user to segment themselves. Win-win.

![screen shot 2017-11-08 at 12 08 45 pm](https://user-images.githubusercontent.com/540990/32566805-2cb42632-c487-11e7-9290-1dd4ded30522.png)

**Comment by JiveDig** [comment]
This is a select field and the ‘value’ of each option could/should be passed as a tag. This should work for select/checkbox/radio IMO. This would be a really powerful addition IMO. Right now we're stuck with code (http://help.convertkit.com/article/34-build-a-custom-tag-select-box), but this allows a user to segment themselves. Win-win.

![screen shot 2017-11-08 at 12 08 45 pm](https://user-images.githubusercontent.com/540990/32566805-2cb42632-c487-11e7-9290-1dd4ded30522.png)

**Comment by JiveDig** [comment]
This is a select field and the ‘value’ of each option could/should be passed as a tag. This should work for select/checkbox/radio IMO. This would be a really powerful addition IMO. Right now we're stuck with code (http://help.convertkit.com/article/34-build-a-custom-tag-select-box), but this allows a user to segment themselves. Win-win.

![screen shot 2017-11-08 at 12 08 45 pm](https://user-images.githubusercontent.com/540990/32566805-2cb42632-c487-11e7-9290-1dd4ded30522.png)

**Comment by JiveDig** [comment]
Probably obvious, but...

![forms_ _civilized_caveman_cooking_creations_ _wordpress](https://user-images.githubusercontent.com/540990/32566950-b75bce16-c487-11e7-8e87-6e883c6cd7e7.png)

**Comment by s220284** [comment]
This would be really useful.

**Comment by n7studios** [comment]
Closing as added to 1.2.1 in [this PR](https://github.com/ConvertKit/convertkit-gravity-forms/pull/36), and available on [WordPress](https://wordpress.org/plugins/convertkit-gravity-forms/)
