### ISSUE TITLE
Check on processing partial entries.

### ISSUE THREAD

**Issue by growdev** [ConvertKit/convertkit-gravity-forms#15]
Request: 

> In a multipage form (generated in gravity forms), each page has a "next" buttons and contains for example:
form page 1: name, email
form page 2: demographic data
form page 3: product interest data
form page x: other
>
>Gravity forms has an addon that collects data from each "next" button click = partial entry
>
>And convertkit has an addon that sends the COMPLETE set of data from the form back to convertkit subscriber profile (when hitting the send buttton at the end of the form only, not when hitting "next").
>
>I want to send the data at each click, even when prospects don't complete the totality of the multipage form.

ref: https://secure.helpscout.net/conversation/549470280/193810/

**Comment by n7studios** [comment]
Closing as no other requests for this at this time.
