### ISSUE TITLE
Add better error handling around api calls

### ISSUE THREAD

**Issue by growdev** [ConvertKit/convertkit-gravity-forms#20]
This customer:
https://wordpress.org/support/topic/php-fatal-error-uncaught-error-cannot-use-object-of-type-wp_error-as-array/

Reported that in [this api call](https://github.com/ConvertKit/convertkit-gravity-forms/blob/master/components/gravityforms/class-gf-convertkit.php#L164-L165) a WP_Error was returned. 

This can be caused by not having an API Key entered in the settings page, or a connectivity issue between the website and the CK API server.

Either way, there should be some better error handling when a WP_Error happens communicating to the CK API.

**Comment by n7studios** [comment]
Closing as added to 1.2.1 in [this PR](https://github.com/ConvertKit/convertkit-gravity-forms/pull/36)
